# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: crm_x_development
  username: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: crm_x_test
  username: root
  host: localhost

production:
  adapter: pg
  encoding: utf8
  database: d2llbvuv5q7lbl
  username: ktropmwobecpyp
  password: ZU4F7VagyxgigZv-SelYpkDxMY
  port: 5432
  host: ec2-54-197-241-67.compute-1.amazonaws.com